sudo: required
services:
  - docker

before_install:
  - docker build -t easternts2021/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true easternts2021/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aws"
  env: "Dockeraws-env"
  bucket_name: "elasticbeanstalk-us-east-2-974606206296"
  bucket_path: "docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  